Add a no-op WavefrontSender implementation
wavefrontHQ/wavefront-sdk-go pull request #65
Opened 2021-06-21 19:36 UTC by mssrinivas

2021-06-22 21:03 UTC, oppegard requested changes
Thanks for the submission @mssrinivas! Could you give an example of your use-case that requires a no-op Sender, rather than just not instantiating a Sender at all?

2021-06-22 22:57 UTC, mssrinivas commented
@oppegard  We have a service A currently using DirectConfig to send metrics to WF. We also have another service B which implements interfaces of service A but do not want to enable metrics capturing. Since things are tightly coupled we wanted to have a way to initialize Noop sender.

2021-06-23 16:18 UTC, oppegard approved these changes

2021-06-23 20:32 UTC, hanwavefront approved these changes
LGTM, thanks!

2021-06-23 20:48 UTC, oppegard approved these changes

2021-06-23 21:21 UTC, merged